---
- name: Install and configure Nginx
  hosts: web_servers                 # under the name web_servers in /etc/ansible/hosts i have both ubuntu and red-hat servers configured. I have to install nginx only in ubuntu server, hence i have used when condition in the playbook
  become: true                        # Run tasks as sudo

  tasks:
    - name: Update apt cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'

    - name: Copy Nginx config file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Reload Nginx
      when: ansible_os_family == 'Debian'

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
